"use client";

import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";
import {
  ArrowRight,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheckBig,
  Compass,
  FolderKanban,
  GraduationCap,
  Menu,
  Play,
  Search,
  Sparkles,
  Star,
  Trophy,
  Users,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const navigation = [
  { label: "How it works", href: "#how-it-works" },
  { label: "Discover", href: "#discover" },
  { label: "For communities", href: "#communities" },
  { label: "Events", href: "/events/extension-board-2026" },
];

const features: { icon: LucideIcon; title: string; description: string; tone: string; iconTone: string }[] = [
  { icon: Compass, title: "Discover what matters", description: "Find projects, student communities, events, resources, and opportunities that suit where you want to go.", tone: "from-blue-50 to-white", iconTone: "bg-blue-100 text-blue-600" },
  { icon: Users, title: "Find your people", description: "Meet teammates with complementary skills, join serious communities, and build a campus network with momentum.", tone: "from-violet-50 to-white", iconTone: "bg-violet-100 text-violet-600" },
  { icon: FolderKanban, title: "Turn ambition into proof", description: "Keep projects visible, organise your work, and build a profile that opens real doors after college.", tone: "from-emerald-50 to-white", iconTone: "bg-emerald-100 text-emerald-600" },
];

const steps = [
  { number: "01", title: "Build your student profile", description: "Your interests, skills, course, and goals create a workspace that feels personal from day one.", icon: GraduationCap, tone: "bg-blue-600" },
  { number: "02", title: "Explore your campus universe", description: "Use one calm, searchable home for events, teams, resources, and opportunities.", icon: Search, tone: "bg-violet-600" },
  { number: "03", title: "Make progress visible", description: "Share projects, join the right rooms, and keep track of what moves you forward.", icon: Sparkles, tone: "bg-emerald-600" },
];

const testimonials = [
  { quote: "I found two teammates for our energy-monitoring prototype and a mentor who helped us improve the demo.", name: "Aarav Mehta", detail: "Electrical Engineering · 3rd year", initials: "AM", color: "from-blue-100 to-cyan-100" },
  { quote: "CampusLoop makes opportunities feel discoverable instead of buried in ten different WhatsApp groups.", name: "Nandini Rao", detail: "Computer Science · 2nd year", initials: "NR", color: "from-violet-100 to-fuchsia-100" },
  { quote: "Our club finally has one space for applications, event updates, project teams, and resources.", name: "Karan Shah", detail: "Robotics Club Lead", initials: "KS", color: "from-emerald-100 to-teal-100" },
];

const faqs = [
  { question: "Who is CampusLoop for?", answer: "CampusLoop is built for students, student communities, mentors, faculty teams, and early-career builders who want their campus work to connect." },
  { question: "Is CampusLoop free for students?", answer: "Yes. Students can create a profile, discover opportunities, explore communities, and organise projects through the core experience." },
  { question: "Can a club or college team use it?", answer: "Yes. Communities can use CampusLoop as a home for members, events, applications, resources, and team collaboration." },
];

const fadeUp = { hidden: { opacity: 0, y: 22 }, visible: { opacity: 1, y: 0 } };

export default function HomePage() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);

  return (
    <main className="min-h-screen overflow-hidden bg-[#f8f9fc] text-slate-950">
      <div className="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
        <div className="absolute -left-36 -top-40 h-[36rem] w-[36rem] rounded-full bg-blue-200/40 blur-[110px]" />
        <div className="absolute -right-44 top-[22rem] h-[34rem] w-[34rem] rounded-full bg-violet-100/80 blur-[120px]" />
        <div className="absolute bottom-[5%] left-[25%] h-[28rem] w-[28rem] rounded-full bg-emerald-100/50 blur-[120px]" />
      </div>

      <header className="relative z-40 mx-auto max-w-7xl px-4 pt-4 sm:px-6 lg:px-8">
        <nav className="flex h-16 items-center justify-between rounded-2xl border border-white/80 bg-white/75 px-4 shadow-[0_10px_35px_rgba(15,23,42,0.06)] backdrop-blur-xl sm:px-5">
          <Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-blue-600 to-indigo-600 text-white shadow-lg shadow-blue-600/25"><GraduationCap className="h-5 w-5" /></span><span className="text-lg font-bold tracking-[-0.05em]">Campus<span className="text-blue-600">Loop</span></span></Link>
          <div className="hidden items-center gap-7 lg:flex">{navigation.map((item) => <Link key={item.label} href={item.href} className="text-sm font-semibold text-slate-500 transition hover:text-blue-600">{item.label}</Link>)}</div>
          <div className="hidden items-center gap-3 sm:flex"><Link href="/login" className="rounded-xl px-4 py-2 text-sm font-bold text-slate-600 transition hover:bg-slate-100">Sign in</Link><Link href="/signup" className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-md shadow-blue-600/20 transition hover:-translate-y-0.5 hover:bg-blue-700">Join CampusLoop</Link></div>
          <button type="button" aria-label="Open navigation" onClick={() => setMobileOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl text-slate-600 hover:bg-slate-100 sm:hidden"><Menu className="h-5 w-5" /></button>
        </nav>
        <AnimatePresence>{mobileOpen && <motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className="absolute inset-x-4 top-[4.75rem] rounded-2xl border border-slate-100 bg-white p-4 shadow-2xl sm:hidden"><div className="flex justify-end"><button type="button" aria-label="Close navigation" onClick={() => setMobileOpen(false)} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-50 text-slate-500"><X className="h-4 w-4" /></button></div><div className="mt-2 space-y-1">{navigation.map((item) => <Link key={item.label} href={item.href} onClick={() => setMobileOpen(false)} className="block rounded-xl px-3 py-3 text-sm font-bold text-slate-700 hover:bg-blue-50 hover:text-blue-700">{item.label}</Link>)}</div><Link href="/signup" onClick={() => setMobileOpen(false)} className="mt-3 flex items-center justify-center rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Join CampusLoop</Link></motion.div>}</AnimatePresence>
      </header>

      <section className="relative mx-auto max-w-7xl px-4 pb-16 pt-16 sm:px-6 sm:pb-24 sm:pt-20 lg:px-8 lg:pb-28 lg:pt-28">
        <motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: 0.09 } } }} className="grid items-center gap-12 lg:grid-cols-[1fr_0.93fr] lg:gap-16">
          <div>
            <motion.div variants={fadeUp} className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3.5 py-2 text-xs font-bold text-blue-700"><span className="h-2 w-2 rounded-full bg-blue-600" /> Built for the student life you actually live</motion.div>
            <motion.h1 variants={fadeUp} className="mt-6 max-w-3xl text-4xl font-bold leading-[1.02] tracking-[-0.065em] text-slate-950 sm:text-5xl lg:text-6xl">Your entire campus life, <span className="text-blue-600">beautifully connected.</span></motion.h1>
            <motion.p variants={fadeUp} className="mt-6 max-w-xl text-base leading-7 text-slate-600 sm:text-lg">CampusLoop turns scattered groups, missed deadlines, and hidden opportunities into one calm place to learn, build, belong, and move forward.</motion.p>
            <motion.div variants={fadeUp} className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="group inline-flex items-center justify-center gap-2 rounded-2xl bg-blue-600 px-5 py-3.5 text-sm font-bold text-white shadow-xl shadow-blue-600/25 transition hover:-translate-y-0.5 hover:bg-blue-700">Create your student space <ArrowRight className="h-4 w-4 transition group-hover:translate-x-0.5" /></Link><Link href="#how-it-works" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 py-3.5 text-sm font-bold text-slate-700 transition hover:border-blue-200 hover:text-blue-700"><Play className="h-4 w-4 fill-current" /> See how it works</Link></motion.div>
            <motion.div variants={fadeUp} className="mt-9 flex flex-wrap items-center gap-x-6 gap-y-3 text-xs font-semibold text-slate-500"><span className="flex items-center gap-2"><CircleCheckBig className="h-4 w-4 text-emerald-500" /> Free for students</span><span className="flex items-center gap-2"><CircleCheckBig className="h-4 w-4 text-emerald-500" /> Built for campus life</span><span className="flex items-center gap-2"><CircleCheckBig className="h-4 w-4 text-emerald-500" /> Your profile, your progress</span></motion.div>
          </div>
          <motion.div variants={fadeUp} className="relative mx-auto w-full max-w-[570px] lg:ml-auto">
            <div className="absolute -left-8 top-12 hidden rounded-2xl border border-white/90 bg-white/90 p-3 shadow-xl shadow-slate-900/10 backdrop-blur sm:block"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><Trophy className="h-4 w-4" /></span><span><span className="block text-xs font-bold text-slate-800">New event match</span><span className="block text-[10px] text-slate-400">Just for your interests</span></span></div></div>
            <div className="relative overflow-hidden rounded-[32px] border border-white bg-white p-3 shadow-[0_30px_80px_rgba(15,23,42,0.18)] sm:p-4"><div className="rounded-[23px] bg-[#f7f8fc] p-4 sm:p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-blue-600 text-white"><GraduationCap className="h-4 w-4" /></span><span className="text-sm font-bold">Campus<span className="text-blue-600">Loop</span></span></div><div className="flex gap-2"><span className="h-7 w-7 rounded-lg bg-white" /><span className="h-7 w-7 rounded-full bg-violet-100" /></div></div><div className="mt-6 rounded-2xl bg-slate-950 p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-blue-200">Thursday, August 20</p><div className="mt-3 flex items-end justify-between gap-4"><div><h2 className="text-xl font-bold tracking-tight">Good morning, Aarav.</h2><p className="mt-1 text-xs text-slate-300">Your campus world is moving.</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-blue-100"><Sparkles className="h-5 w-5" /></span></div><div className="mt-5 grid grid-cols-3 gap-2"><MiniStat value="12" label="Matches" /><MiniStat value="3" label="Events" /><MiniStat value="68%" label="Profile" /></div></div><div className="mt-4 grid gap-3 sm:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl border border-slate-100 bg-white p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold text-slate-800">For you</p><ChevronRight className="h-3.5 w-3.5 text-slate-300" /></div><DashboardRow icon={Zap} color="bg-emerald-50 text-emerald-600" title="EV battery internship" meta="Apply by Aug 24" /><DashboardRow icon={Users} color="bg-violet-50 text-violet-600" title="Embedded Builders" meta="3.2K members" /></div><div className="rounded-2xl border border-slate-100 bg-white p-4"><p className="text-xs font-bold text-slate-800">This week</p><div className="mt-4 space-y-3"><div className="rounded-xl bg-blue-50 p-3"><p className="text-[10px] font-bold text-blue-600">SAT · 10:00 AM</p><p className="mt-1 text-xs font-bold text-slate-800">Extension Board</p></div><div className="flex items-center gap-2 text-[10px] font-semibold text-slate-500"><ClockDot /> Project proposal review</div></div></div></div></div></div>
            <div className="absolute -bottom-7 -right-4 hidden rounded-2xl border border-white bg-white p-3 shadow-xl shadow-slate-900/10 sm:block"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-violet-50 text-violet-600"><Users className="h-4 w-4" /></span><span><span className="block text-xs font-bold text-slate-800">Team invite accepted</span><span className="block text-[10px] text-slate-400">Your project just got stronger</span></span></div></div>
          </motion.div>
        </motion.div>
      </section>

      <section className="border-y border-slate-200/80 bg-white/70 py-5"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-10 gap-y-3 px-4 text-center text-xs font-bold uppercase tracking-[0.16em] text-slate-400 sm:px-6"><span>One platform for</span><span className="text-slate-600">Learning</span><span className="text-slate-600">Projects</span><span className="text-slate-600">Communities</span><span className="text-slate-600">Events</span><span className="text-slate-600">Opportunities</span></div></section>

      <section id="discover" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><SectionIntro eyebrow="One connected campus" title="The student experience should not be split across a dozen tabs." description="CampusLoop creates one intentional home for every signal, relationship, and next step that matters." /><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={{ visible: { transition: { staggerChildren: 0.1 } } }} className="mt-10 grid gap-5 md:grid-cols-3">{features.map((feature) => <motion.article variants={fadeUp} key={feature.title} className={`group rounded-[28px] border border-slate-200/70 bg-gradient-to-b ${feature.tone} p-6 transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-slate-900/5 sm:p-7`}><span className={`grid h-12 w-12 place-items-center rounded-2xl ${feature.iconTone}`}><feature.icon className="h-5 w-5" /></span><h3 className="mt-7 text-xl font-bold tracking-[-0.035em] text-slate-900">{feature.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{feature.description}</p><span className="mt-7 inline-flex items-center gap-1 text-xs font-bold text-slate-500 transition group-hover:text-blue-600">Explore more <ArrowRight className="h-3.5 w-3.5" /></span></motion.article>)}</motion.div></section>

      <section id="how-it-works" className="bg-slate-950 py-20 text-white sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.83fr_1.17fr] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-blue-300">How it works</p><h2 className="mt-4 text-3xl font-bold tracking-[-0.055em] sm:text-4xl">Your campus world starts feeling intentional.</h2><p className="mt-5 max-w-md text-sm leading-7 text-slate-300">No more lost links or scattered updates. CampusLoop quietly connects the parts of student life that deserve to work together.</p><Link href="/signup" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-blue-200 transition hover:text-white">Start your student space <ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-4 sm:grid-cols-3">{steps.map((step) => <article key={step.number} className="rounded-3xl border border-white/10 bg-white/[0.06] p-5 backdrop-blur-sm"><span className={`grid h-10 w-10 place-items-center rounded-xl ${step.tone} text-sm font-bold text-white`}>{step.number}</span><step.icon className="mt-9 h-5 w-5 text-blue-200" /><h3 className="mt-4 text-lg font-bold tracking-tight">{step.title}</h3><p className="mt-3 text-xs leading-6 text-slate-300">{step.description}</p></article>)}</div></div></div></section>

      <section id="communities" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><div className="relative order-2 lg:order-1"><div className="rounded-[32px] border border-slate-200 bg-white p-5 shadow-[0_25px_70px_rgba(15,23,42,0.08)] sm:p-7"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-600">Community home</p><p className="mt-1 text-lg font-bold text-slate-900">Robotics & Automation</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-[10px] font-bold text-emerald-700">Verified club</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><InfoCard icon={Users} label="Members" value="1,842" tone="bg-blue-50 text-blue-600" /><InfoCard icon={FolderKanban} label="Projects" value="42" tone="bg-violet-50 text-violet-600" /><InfoCard icon={CalendarDays} label="Upcoming" value="06" tone="bg-emerald-50 text-emerald-600" /></div><div className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><p className="text-sm font-bold text-slate-800">Next event</p><span className="text-[10px] font-bold text-blue-600">See calendar</span></div><div className="mt-4 flex items-center gap-3 rounded-xl bg-white p-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-50 text-orange-600"><Zap className="h-4 w-4" /></span><div className="flex-1"><p className="text-xs font-bold text-slate-800">Rapid prototyping workshop</p><p className="mt-1 text-[10px] text-slate-500">Saturday · Innovation Lab · 10:00 AM</p></div><ChevronRight className="h-4 w-4 text-slate-300" /></div></div></div></div><div className="order-1 lg:order-2"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-blue-600">For student communities</p><h2 className="mt-4 text-3xl font-bold tracking-[-0.055em] text-slate-950 sm:text-4xl">Give your community a home worth joining.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-slate-600">A single, welcoming space for members, events, resources, applications, and the projects that make your club matter.</p><ul className="mt-7 space-y-4">{["Keep events, announcements, and applications together", "Help members discover teams and active projects", "Give new students a clear way to join and contribute"].map((item) => <li key={item} className="flex gap-3 text-sm font-semibold text-slate-700"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" />{item}</li>)}</ul><Link href="/signup" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:bg-blue-700">Bring your community in <ArrowRight className="h-4 w-4" /></Link></div></div></section>

      <section className="border-y border-slate-200/80 bg-white py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionIntro eyebrow="Made for real momentum" title="A better kind of campus network." description="Students do their best work when useful people and useful opportunities are easy to find." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{testimonials.map((testimonial) => <figure key={testimonial.name} className="rounded-[28px] border border-slate-200 bg-[#fbfcff] p-6"><div className="flex gap-1 text-amber-400">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className="h-3.5 w-3.5 fill-current" />)}</div><blockquote className="mt-5 text-base font-semibold leading-7 tracking-[-0.015em] text-slate-800">“{testimonial.quote}”</blockquote><figcaption className="mt-7 flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-full bg-gradient-to-br ${testimonial.color} text-xs font-bold text-slate-700`}>{testimonial.initials}</span><span><span className="block text-sm font-bold text-slate-800">{testimonial.name}</span><span className="mt-0.5 block text-xs text-slate-500">{testimonial.detail}</span></span></figcaption></figure>)}</div></div></section>

      <section className="mx-auto max-w-4xl px-4 py-20 sm:px-6 sm:py-28"><SectionIntro eyebrow="Frequently asked" title="Questions, answered." description="Everything you need to know before making CampusLoop your home on campus." /><div className="mt-10 divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white px-5 shadow-sm sm:px-7">{faqs.map((faq, index) => <div key={faq.question}><button type="button" onClick={() => setOpenFaq(openFaq === index ? -1 : index)} className="flex w-full items-center justify-between gap-5 py-5 text-left text-sm font-bold text-slate-800"><span>{faq.question}</span><ChevronDown className={`h-4 w-4 shrink-0 text-slate-400 transition ${openFaq === index ? "rotate-180" : ""}`} /></button><AnimatePresence initial={false}>{openFaq === index && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><p className="max-w-2xl pb-5 text-sm leading-6 text-slate-600">{faq.answer}</p></motion.div>}</AnimatePresence></div>)}</div></section>

      <section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6 sm:pb-28 lg:px-8"><div className="relative overflow-hidden rounded-[34px] bg-blue-600 px-6 py-12 text-center text-white shadow-2xl shadow-blue-600/25 sm:px-10 sm:py-16"><div className="absolute -left-16 top-0 h-52 w-52 rounded-full bg-white/10 blur-3xl" /><div className="absolute -right-20 bottom-[-6rem] h-64 w-64 rounded-full bg-violet-500/50 blur-3xl" /><div className="relative"><span className="mx-auto grid h-11 w-11 place-items-center rounded-2xl bg-white/15 text-white"><GraduationCap className="h-5 w-5" /></span><h2 className="mx-auto mt-6 max-w-2xl text-3xl font-bold tracking-[-0.055em] sm:text-4xl">Make your time on campus count for more.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-blue-100">Join the students and communities turning daily campus life into meaningful progress.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3.5 text-sm font-bold text-blue-700 transition hover:-translate-y-0.5 hover:bg-blue-50">Create your free account <ArrowRight className="h-4 w-4" /></Link><Link href="/login" className="inline-flex items-center justify-center rounded-2xl border border-white/30 px-5 py-3.5 text-sm font-bold text-white transition hover:bg-white/10">I already have an account</Link></div></div></div></section>

      <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-8 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><Link href="/" className="flex items-center gap-2 text-sm font-bold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-600 text-white"><GraduationCap className="h-4 w-4" /></span>Campus<span className="-ml-2 text-blue-600">Loop</span></Link><p className="text-xs text-slate-400">One campus. More momentum.</p><div className="flex gap-5 text-xs font-semibold text-slate-500"><Link href="/login" className="hover:text-blue-600">Sign in</Link><Link href="/signup" className="hover:text-blue-600">Create account</Link><Link href="/events/extension-board-2026" className="hover:text-blue-600">Events</Link></div></div></footer>
    </main>
  );
}

function MiniStat({ value, label }: { value: string; label: string }) { return <div className="rounded-xl bg-white/[0.09] px-3 py-2.5"><p className="text-sm font-bold">{value}</p><p className="mt-0.5 text-[9px] text-slate-300">{label}</p></div>; }
function DashboardRow({ icon: Icon, color, title, meta }: { icon: LucideIcon; color: string; title: string; meta: string }) { return <div className="mt-3 flex items-center gap-2"><span className={`grid h-8 w-8 place-items-center rounded-lg ${color}`}><Icon className="h-3.5 w-3.5" /></span><span className="min-w-0"><span className="block truncate text-[10px] font-bold text-slate-700">{title}</span><span className="block text-[9px] text-slate-400">{meta}</span></span></div>; }
function ClockDot() { return <span className="h-2 w-2 rounded-full bg-emerald-500" />; }
function SectionIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="mx-auto max-w-2xl text-center"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-blue-600">{eyebrow}</p><h2 className="mt-4 text-3xl font-bold tracking-[-0.055em] text-slate-950 sm:text-4xl">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-600 sm:text-base">{description}</p></div>; }
function InfoCard({ icon: Icon, label, value, tone }: { icon: LucideIcon; label: string; value: string; tone: string }) { return <div className="rounded-2xl border border-slate-100 p-3"><span className={`grid h-8 w-8 place-items-center rounded-lg ${tone}`}><Icon className="h-3.5 w-3.5" /></span><p className="mt-4 text-lg font-bold text-slate-900">{value}</p><p className="text-[10px] font-semibold text-slate-400">{label}</p></div>; }
