import Link from "next/link";
import { Check, ChevronRight, LockKeyhole } from "lucide-react";

const plans = [
  { name: "Free", price: "₹0", cadence: "forever", description: "A useful campus workspace without artificial lockouts", features: ["Student profile", "Public events and free registration", "Basic projects and campus discovery", "Limited AI assistance"] },
  { name: "30-day Premium Trial", price: "₹0", cadence: "for 30 days", description: "Premium access for eligible new students, with no card required", features: ["Advanced campus guidance", "Richer project and opportunity planning", "Premium workspace enhancements", "No automatic payment"] },
  { name: "Premium Monthly", price: "₹400", cadence: "per month", description: "Extended CampusLoop support for an active semester", features: ["Everything in trial", "Advanced personalization", "Longer guidance workflows", "Premium feature access"] },
  { name: "Premium Yearly", price: "₹4,000", cadence: "per year", description: "The annual plan for students building over the full year", features: ["Everything in monthly", "₹800 saved vs 12 monthly payments", "One clear annual charge", "Premium feature access"] },
];

export default function PricingPage() {
  return <main className="min-h-screen bg-[#050816] px-5 py-10 text-slate-100 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><header className="flex flex-col gap-6 border-b border-white/10 pb-10 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-cyan-300">CampusLoop plans</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em] text-white sm:text-6xl">More context. More momentum.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-400">Choose the level of support that fits your campus journey. The free workspace remains useful, and the trial never asks for payment details.</p></div><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-cyan-300 hover:text-white">Back to workspace <ChevronRight className="h-4 w-4" /></Link></header><div className="mt-10 grid gap-5 lg:grid-cols-4">{plans.map((plan) => <article key={plan.name} className={`premium-surface rounded-[28px] border p-6 ${plan.name === "Premium Monthly" ? "border-cyan-300/40 bg-cyan-300/[0.07]" : "border-white/10 bg-white/[0.035]"}`}><p className="text-sm font-semibold text-white">{plan.name}</p><p className="mt-7 text-4xl font-semibold tracking-[-0.06em] text-white">{plan.price}</p><p className="mt-1 text-xs uppercase tracking-[0.16em] text-slate-500">{plan.cadence}</p><p className="mt-5 min-h-20 text-sm leading-6 text-slate-400">{plan.description}</p><ul className="mt-6 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex gap-2 text-sm text-slate-300"><Check className="mt-0.5 h-4 w-4 shrink-0 text-cyan-300" />{feature}</li>)}</ul>{plan.name === "Free" ? <Link href="/signup" className="mt-8 inline-flex w-full items-center justify-center rounded-2xl border border-white/10 px-4 py-3 text-sm font-semibold text-white hover:bg-white/5">Create account</Link> : <div className="mt-8 rounded-2xl border border-white/10 bg-black/10 px-4 py-3 text-xs leading-5 text-slate-500"><LockKeyhole className="mb-2 h-4 w-4 text-slate-400" />Payment setup is not connected in this build. No purchase is simulated.</div>}</article>)}</div><p className="mt-8 text-center text-xs text-slate-600">Premium billing remains intentionally disabled until a payment provider and server-side entitlement flow are connected.</p></div></main>;
}
